version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - ${DATBASE_PORT:-5432}:5432

  migrations:
    image: $BASE_IMAGE_NODE_ALPINE
    command: yarn dev
    env_file:
      - .env
    working_dir: /apps/database
    volumes:
      - ./apps/database:/apps/database
    depends_on:
      - db

  gql:
    image: $BASE_IMAGE_NODE_ALPINE
    command: yarn dev
    working_dir: /apps/graphql
    env_file:
      - .env
    volumes:
      - ./apps/graphql:/apps/graphql
    ports:
      - ${GRAPHQL_PORT:-5000}:5000
    depends_on:
      - migrations

  worker:
    image: $BASE_IMAGE_NODE_ALPINE
    command: yarn dev
    working_dir: /apps/worker
    env_file:
      - .env
    volumes:
      - ./apps/worker:/apps/worker
    depends_on:
      - migrations

volumes:
  pg_data:
