version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: $DATABASE_OWNER
      POSTGRES_PASSWORD: $DATABASE_OWNER_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  migrations:
    image: $BASE_IMAGE_NODE_ALPINE
    working_dir: /apps/database
    volumes:
      - ./apps/database:/apps/database
    env_file:
      - .env
    depends_on:
      - db

  gql:
    image: $BASE_IMAGE_NODE_ALPINE
    working_dir: /apps/graphql
    volumes:
      - ./apps/graphql:/graphql
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - migrations

volumes:
  pg_data:
