version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: $DATABASE_OWNER
      POSTGRES_PASSWORD: $DATABASE_OWNER_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  migrations:
    environment:
      ROOT_DATABASE_URL: postgres://$DATABASE_OWNER:$DATABASE_OWNER_PASSWORD@$DATABASE_HOST/template1
      SHADOW_DATABASE_URL: postgres://$DATABASE_OWNER:$DATABASE_OWNER_PASSWORD@$DATABASE_HOST/${DATABASE_NAME}_shadow
    build:
      context: .
      dockerfile: apps/database/Dockerfile
      target: dev
      args:
        BASE_IMAGE: $BASE_IMAGE_NODE_ALPINE
    volumes:
      - ./apps/database:/apps/database
    env_file:
      - .env
    depends_on:
      - db

  gql:
    environment:
      AUTH_DATABASE_URL: postgres://$DATABASE_AUTHENTICATOR:$DATABASE_AUTHENTICATOR_PASSWORD@$DATABASE_HOST/$DATABASE_NAME
      SECRET: SUPERSECRETE
      NODE_ENV: development
    build:
      context: .
      dockerfile: apps/graphql/Dockerfile
      target: dev
      args:
        BASE_IMAGE: $BASE_IMAGE_NODE_ALPINE
    volumes:
      - ./apps/web:/apps/web:ro
      - ./apps/graphql:/apps/graphql
    env_file:
      - .env
    depends_on:
      - migrations
    ports:
      - 5000:5000

volumes:
  pg_data:
