version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - ${DATBASE_PORT:-5432}:5432

  migrations:
    image: $BASE_IMAGE_NODE_ALPINE
    working_dir: /apps/database
    volumes:
      - ./apps/database:/apps/database
    env_file:
      - .env
    depends_on:
      - db

  gql:
    image: $BASE_IMAGE_NODE_ALPINE
    working_dir: /apps/graphql
    volumes:
      - ./apps/graphql:/graphql
    env_file:
      - .env
    ports:
      - ${GRAPHQL_PORT:-5000}:5000
    depends_on:
      - migrations

volumes:
  pg_data:
