version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  migrations:
    build:
      context: .
      dockerfile: apps/database/Dockerfile
    volumes:
      - ./apps/database:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
