apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-root-credentials
data:
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-database-owner-url-credentials
data:
  DATABASE_URL: {{ include "postgres.databaseURI" . | b64enc | quote }}
